/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import beans.Cliente;
import beans.Convenio;
import beans.Estadocivil;
import beans.Sexo;
import controller.ClienteController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.eclipse.persistence.exceptions.DatabaseException;
import util.ConfigTelas;
import util.ConfigurationFactory;
import util.ConnectionFactory;
import util.ValidarValores;

/**
 *
 * @author Produção
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    Cliente c = new Cliente();

    /**
     * Creates new form TelaPadrao
     */
    public TelaCadastroCliente() {
        initComponents();
        ConfigTelas ct = new ConfigTelas(this);
        ct.carregarConfig(this);

    }

    public TelaCadastroCliente(Cliente cli) {
        initComponents();

        this.c = cli;
        preencheCampos();
        ConfigTelas ct = new ConfigTelas(this);
        ct.carregarConfig(this);
        jButtonPesquisa.setEnabled(false);
    }

    private void preencheCampos() {
        jTextFieldCodigo.setEnabled(false);
        jComboBoxConvenio.setSelectedItem(this.c.getIdconvenio());
        jComboBoxSexo.setSelectedItem(this.c.getIdsexo());
        jComboBoxEstadoCivil.setSelectedItem(this.c.getIdestadocivil());
        jTextFieldCodigo.setText(this.c.getIdcliente().toString());

        if (this.c.getNome() != null) {
            jTextFieldNome.setText(this.c.getNome());
        }

        if (this.c.getTelefone() != null) {
            jTextFieldTelefone.setText(this.c.getTelefone());
        }

        if (this.c.getEndereco() != null) {
            jTextFieldEndereco.setText(this.c.getEndereco());
        }

        if (this.c.getEndereconr() != null) {
            jTextFieldEnderecoNr.setText(this.c.getEndereconr());
        }

        if (this.c.getBairro() != null) {
            jTextFieldBairro.setText(this.c.getBairro());
        }

        if (this.c.getCpf() != null) {
            jTextFieldCPF.setText(this.c.getCpf());
        }

        if (this.c.getIdentidade() != null) {
            jTextFieldRG.setText(this.c.getIdentidade());
        }

        if (this.c.getNaturalidade() != null) {
            jTextFieldNaturalidade.setText(this.c.getNaturalidade());
        }

        if (this.c.getPai() != null) {
            jTextFieldNomePai.setText(this.c.getPai());
        }

        if (this.c.getMae() != null) {
            jTextFieldNomeMae.setText(this.c.getMae());
        }

        if (this.c.getEmprego() != null) {
            jTextFieldEmprego.setText(this.c.getEmprego());
        }

        if (this.c.getCargo() != null) {
            jTextFieldCargo.setText(this.c.getCargo());
        }

        if (this.c.getDataadmissao() != null) {
            jDateChooserAdmissao.setDate(this.c.getDataadmissao());
        }

        if (this.c.getRenda() != null) {
            jFormattedTextFieldRenda.setText(this.c.getRenda().toString());
        }

        if (this.c.getLimite() != null) {
            jFormattedTextFieldLimite.setText(this.c.getLimite().toString());
        }

        if (this.c.getDatanasc() != null) {
            jDateChooser1.setDate(this.c.getDatanasc());
        }
        
        if (this.c.getTotalAberto() != null){
            jFormattedTextFieldAberto.setValue(this.c.getTotalAberto());
        }
        
        if (this.c.getTotalGasto()!= null){
            jFormattedTextFieldGasto.setValue(this.c.getTotalGasto());
        }
        

        jTextAreaObservacao.setText(this.c.getObservacao());
        jComboBoxSituacao.setSelectedItem(this.c.getSituacao());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTextField3 = new javax.swing.JTextField();
        convenioListCellRenderer1 = new renderizadores.ConvenioListCellRenderer();
        estadoCivilListCellRenderer1 = new renderizadores.EstadoCivilListCellRenderer();
        sexoListCellRenderer1 = new renderizadores.SexoListCellRenderer();
        convenioPUEntityManager = ConnectionFactory.getEntityManager();
        convenioQuery = java.beans.Beans.isDesignTime() ? null : convenioPUEntityManager.createQuery("SELECT c FROM Convenio c");
        convenioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : convenioQuery.getResultList();
        sexoQuery = java.beans.Beans.isDesignTime() ? null : convenioPUEntityManager.createQuery("SELECT s FROM Sexo s");
        sexoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : sexoQuery.getResultList();
        estadocivilQuery = java.beans.Beans.isDesignTime() ? null : convenioPUEntityManager.createQuery("SELECT e FROM Estadocivil e");
        estadocivilList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : estadocivilQuery.getResultList();
        valorTableCellRenderer1 = new renderizadores.ValorTableCellRenderer();
        jPanel1 = new javax.swing.JPanel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jComboBoxConvenio = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldEnderecoNr = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldRG = new javax.swing.JTextField();
        jTextFieldNaturalidade = new javax.swing.JTextField();
        jTextFieldNomePai = new javax.swing.JTextField();
        jTextFieldNomeMae = new javax.swing.JTextField();
        jTextFieldEmprego = new javax.swing.JTextField();
        jTextFieldCargo = new javax.swing.JTextField();
        jDateChooserAdmissao = new com.toedter.calendar.JDateChooser();
        jFormattedTextFieldLimite = new javax.swing.JFormattedTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jFormattedTextFieldRenda = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacao = new javax.swing.JTextArea();
        jComboBoxSituacao = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextFieldGasto = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jFormattedTextFieldAberto = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldTelefone1 = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        convenioListCellRenderer1.setText("convenioListCellRenderer1");

        estadoCivilListCellRenderer1.setText("estadoCivilListCellRenderer1");

        sexoListCellRenderer1.setText("sexoListCellRenderer1");

        valorTableCellRenderer1.setText("valorTableCellRenderer1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButtonVoltar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/8416_32x32.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonGravar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/save.png"))); // NOI18N
        jButtonGravar.setText("Gravar");
        jButtonGravar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGravar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/6155_32x32.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Cliente");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setText("Código:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 16, 70, 20);

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(10, 36, 62, 28);

        jComboBoxConvenio.setRenderer(convenioListCellRenderer1);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, convenioList, jComboBoxConvenio);
        bindingGroup.addBinding(jComboBoxBinding);

        jPanel2.add(jComboBoxConvenio);
        jComboBoxConvenio.setBounds(10, 90, 180, 28);

        jLabel3.setText("Sexo:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(200, 70, 60, 20);

        jComboBoxSexo.setRenderer(sexoListCellRenderer1);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sexoList, jComboBoxSexo);
        bindingGroup.addBinding(jComboBoxBinding);

        jPanel2.add(jComboBoxSexo);
        jComboBoxSexo.setBounds(200, 90, 60, 28);

        jLabel4.setText("Convênio:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 70, 70, 20);

        jLabel5.setText("Situação:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(540, 70, 140, 20);

        jComboBoxEstadoCivil.setRenderer(estadoCivilListCellRenderer1);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, estadocivilList, jComboBoxEstadoCivil);
        bindingGroup.addBinding(jComboBoxBinding);

        jPanel2.add(jComboBoxEstadoCivil);
        jComboBoxEstadoCivil.setBounds(270, 90, 100, 28);

        jLabel6.setText("Nome:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(90, 16, 90, 20);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNome);
        jTextFieldNome.setBounds(90, 36, 250, 28);

        jLabel7.setText("Limite:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(630, 16, 80, 20);

        jLabel8.setText("Endereço:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 124, 110, 20);

        jLabel9.setText("Renda:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(570, 286, 80, 20);

        jLabel10.setText("Nr:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(380, 124, 70, 20);

        jLabel11.setText("Bairro:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(470, 124, 90, 20);

        jLabel12.setText("CPF:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 178, 50, 20);

        jLabel13.setText("RG:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(260, 178, 50, 20);

        jLabel14.setText("Naturalidade:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(470, 178, 100, 20);

        jLabel15.setText("Nome do pai:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 232, 100, 20);

        jLabel16.setText("Nome da mãe:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(360, 232, 100, 20);

        jLabel17.setText("Observações:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(180, 340, 100, 20);

        jLabel18.setText("Cargo:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(220, 286, 100, 20);

        jLabel19.setText("Data de admissão:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(410, 286, 160, 20);
        jPanel2.add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(350, 36, 130, 28);
        jPanel2.add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(10, 144, 360, 28);
        jPanel2.add(jTextFieldEnderecoNr);
        jTextFieldEnderecoNr.setBounds(380, 144, 80, 28);
        jPanel2.add(jTextFieldBairro);
        jTextFieldBairro.setBounds(470, 144, 230, 30);
        jPanel2.add(jTextFieldCPF);
        jTextFieldCPF.setBounds(10, 198, 220, 28);
        jPanel2.add(jTextFieldRG);
        jTextFieldRG.setBounds(260, 198, 180, 28);
        jPanel2.add(jTextFieldNaturalidade);
        jTextFieldNaturalidade.setBounds(470, 198, 230, 28);
        jPanel2.add(jTextFieldNomePai);
        jTextFieldNomePai.setBounds(10, 252, 340, 28);
        jPanel2.add(jTextFieldNomeMae);
        jTextFieldNomeMae.setBounds(360, 252, 340, 28);
        jPanel2.add(jTextFieldEmprego);
        jTextFieldEmprego.setBounds(10, 306, 200, 28);
        jPanel2.add(jTextFieldCargo);
        jTextFieldCargo.setBounds(220, 306, 180, 28);
        jPanel2.add(jDateChooserAdmissao);
        jDateChooserAdmissao.setBounds(410, 306, 150, 28);

        jFormattedTextFieldLimite.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));
        jFormattedTextFieldLimite.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldLimite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldLimiteFocusGained(evt);
            }
        });
        jFormattedTextFieldLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldLimiteActionPerformed(evt);
            }
        });
        jPanel2.add(jFormattedTextFieldLimite);
        jFormattedTextFieldLimite.setBounds(630, 36, 80, 30);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(380, 90, 150, 28);

        jLabel20.setText("Estado Civil:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(270, 70, 80, 20);

        jFormattedTextFieldRenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jFormattedTextFieldRenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldRendaActionPerformed(evt);
            }
        });
        jPanel2.add(jFormattedTextFieldRenda);
        jFormattedTextFieldRenda.setBounds(570, 306, 130, 30);

        jLabel21.setText("Telefone:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(350, 16, 120, 20);

        jTextAreaObservacao.setColumns(20);
        jTextAreaObservacao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObservacao);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(170, 360, 530, 110);

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ativo", "inativo", "bloqueado" }));
        jPanel2.add(jComboBoxSituacao);
        jComboBoxSituacao.setBounds(540, 90, 160, 30);

        jLabel22.setText("Data de Nascimento:");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(380, 70, 140, 20);

        jLabel23.setText("Emprego:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 286, 100, 20);

        jFormattedTextFieldGasto.setEditable(false);
        jFormattedTextFieldGasto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jFormattedTextFieldGasto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldGasto.setCaretColor(new java.awt.Color(255, 51, 51));
        jFormattedTextFieldGasto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFormattedTextFieldGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldGastoActionPerformed(evt);
            }
        });
        jPanel2.add(jFormattedTextFieldGasto);
        jFormattedTextFieldGasto.setBounds(10, 360, 130, 30);

        jLabel24.setText("Total Gasto:");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 340, 80, 20);

        jFormattedTextFieldAberto.setEditable(false);
        jFormattedTextFieldAberto.setForeground(new java.awt.Color(255, 0, 51));
        jFormattedTextFieldAberto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jFormattedTextFieldAberto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextFieldAberto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFormattedTextFieldAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldAbertoActionPerformed(evt);
            }
        });
        jPanel2.add(jFormattedTextFieldAberto);
        jFormattedTextFieldAberto.setBounds(10, 430, 130, 30);

        jLabel25.setText("Total Aberto:");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(10, 410, 80, 20);

        jLabel26.setText("Celular:");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(490, 16, 120, 20);
        jPanel2.add(jTextFieldTelefone1);
        jTextFieldTelefone1.setBounds(490, 36, 130, 28);

        jButtonPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/32x32/1408_32x32.png"))); // NOI18N
        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPesquisa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(752, 688));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoKeyTyped

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        ClienteController cc = new ClienteController();

        boolean validado = true;
        boolean retorno = false;

        this.c.setIdconvenio((Convenio) jComboBoxConvenio.getSelectedItem());
        this.c.setIdsexo((Sexo) jComboBoxSexo.getSelectedItem());
        this.c.setIdestadocivil((Estadocivil) jComboBoxEstadoCivil.getSelectedItem());
        this.c.setNome(jTextFieldNome.getText());
        this.c.setTelefone(jTextFieldTelefone.getText());
        this.c.setEndereco(jTextFieldEndereco.getText());
        this.c.setEndereconr(jTextFieldEnderecoNr.getText());
        this.c.setBairro(jTextFieldBairro.getText());
        this.c.setCpf(jTextFieldCPF.getText());
        this.c.setIdentidade(jTextFieldRG.getText());
        this.c.setNaturalidade(jTextFieldNaturalidade.getText());
        this.c.setPai(jTextFieldNomePai.getText());
        this.c.setMae(jTextFieldNomeMae.getText());
        this.c.setEmprego(jTextFieldEmprego.getText());
        this.c.setCargo(jTextFieldCargo.getText());
        this.c.setDataadmissao(jDateChooserAdmissao.getDate());
        this.c.setDatanasc(jDateChooser1.getDate());
        this.c.setSituacao(jComboBoxSituacao.getSelectedItem().toString());
        this.c.setObservacao(jTextAreaObservacao.getText());

        try {
            //this.c.setRenda(Double.parseDouble(jFormattedTextFieldRenda.getValue().toString()));
            this.c.setRenda(ValidarValores.converterDoubleDoisDecimais(jFormattedTextFieldRenda.getText()));
        } catch (NumberFormatException nfe) {
            ConfigurationFactory.getLOG().warn(nfe.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Preecha o campo 'Renda'!");
            validado = false;
        } catch (NullPointerException npe) {
            ConfigurationFactory.getLOG().warn(npe.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Preecha o campo 'Renda'!");
            validado = false;
        }

        try {
            this.c.setLimite(ValidarValores.converterDoubleDoisDecimais(jFormattedTextFieldLimite.getText()));
        } catch (NumberFormatException nfe) {
            ConfigurationFactory.getLOG().warn(nfe.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Preecha o campo 'Limite'!");
            validado = false;
        } catch (NullPointerException npe) {
            ConfigurationFactory.getLOG().warn(npe.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Preecha o campo 'Limite'!");
            validado = false;
        }

        if (validado == true) {

            if ((this.c.getIdcliente() == null)) {
                try {
                    retorno = cc.inserir(this.c);

                } catch (SQLException ex) {
                    ConfigurationFactory.getLOG().warn(ex.getMessage());
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                } catch (DatabaseException dbe){
                    ConfigurationFactory.getLOG().warn(dbe.getMessage());
                }

            } else {
                try {
                    retorno = cc.alterar(this.c, validado);

                } catch (SQLException ex) {
                    ConfigurationFactory.getLOG().warn(ex.getMessage());
                }

            }

            if (retorno) {
                new TelaRelacaoClientes().setVisible(true);
                this.dispose();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaRelacaoClientes trc = new TelaRelacaoClientes();
        trc.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jFormattedTextFieldLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldLimiteActionPerformed

    private void jFormattedTextFieldRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldRendaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        this.c = null;

        jTextFieldCodigo.setText(null);
        jTextFieldNome.setText(null);
        jTextFieldTelefone.setText(null);
        jTextField3.setText(null);
        jFormattedTextFieldLimite.setText(null);
        jTextFieldEndereco.setText(null);
        jTextFieldEnderecoNr.setText(null);
        jTextFieldBairro.setText(null);
        jTextFieldCPF.setText(null);
        jTextFieldRG.setText(null);
        jTextFieldNaturalidade.setText(null);
        jTextFieldNomePai.setText(null);
        jTextFieldNomeMae.setText(null);
        jTextFieldEmprego.setText(null);
        jTextFieldCargo.setText(null);
        jFormattedTextFieldRenda.setText(null);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        TelaRelacaoClientes tlc = new TelaRelacaoClientes();
        tlc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jFormattedTextFieldGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldGastoActionPerformed

    private void jFormattedTextFieldAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldAbertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldAbertoActionPerformed

    private void jFormattedTextFieldLimiteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldLimiteFocusGained
        jFormattedTextFieldLimite.selectAll();
    }//GEN-LAST:event_jFormattedTextFieldLimiteFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            ConfigurationFactory.getLOG().warn(ex.getMessage());
        } catch (InstantiationException ex) {
            ConfigurationFactory.getLOG().warn(ex.getMessage());
        } catch (IllegalAccessException ex) {
            ConfigurationFactory.getLOG().warn(ex.getMessage());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            ConfigurationFactory.getLOG().warn(ex.getMessage());
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<beans.Convenio> convenioList;
    private renderizadores.ConvenioListCellRenderer convenioListCellRenderer1;
    private javax.persistence.EntityManager convenioPUEntityManager;
    private javax.persistence.Query convenioQuery;
    private renderizadores.EstadoCivilListCellRenderer estadoCivilListCellRenderer1;
    private java.util.List<beans.Estadocivil> estadocivilList;
    private javax.persistence.Query estadocivilQuery;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox jComboBoxConvenio;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxSituacao;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooserAdmissao;
    private javax.swing.JFormattedTextField jFormattedTextFieldAberto;
    private javax.swing.JFormattedTextField jFormattedTextFieldGasto;
    private javax.swing.JFormattedTextField jFormattedTextFieldLimite;
    private javax.swing.JFormattedTextField jFormattedTextFieldRenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaObservacao;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEmprego;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEnderecoNr;
    private javax.swing.JTextField jTextFieldNaturalidade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeMae;
    private javax.swing.JTextField jTextFieldNomePai;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldTelefone1;
    private java.util.List<beans.Sexo> sexoList;
    private renderizadores.SexoListCellRenderer sexoListCellRenderer1;
    private javax.persistence.Query sexoQuery;
    private renderizadores.ValorTableCellRenderer valorTableCellRenderer1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
